format = """
$username\
$directory\
$git_branch\
$git_status\
$docker_context\
$cmd_duration\
\n$character\
"""

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#0E9AA7 bold"
style_root = "fg:#FE8A71 bold"
format = '[$user ]($style)'
disabled = false

[directory]
style = "fg:#B7C6E7"
format = "[in $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ' '
style = "fg:#FCA17D"
format = '[ on $symbol$branch ]($style)'

[git_status]
conflicted = "󱠱 "
ahead = "⇡ $count "
behind = "⇣ $count "
untracked = " ×${count} "
stashed = "󱉼 "
modified = " ×${count} "
staged = " ×${count} "
renamed = " ×${count} "
deleted = " ×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[cmd_duration]
min_time = 1
show_milliseconds = false
disabled = false
style = "bold italic red"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"
vimcmd_symbol = "[<](bold green)"
