[window]
dimensions = { columns=110, lines=30 }
opacity = 0.9
padding.x = 1
padding.y = 1
decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold.style = "Bold"
italic.style = "Italic"
bold_italic.style = "Bold Italic"
size = 10.0

[selection]
save_to_clipboard=true

[env]
TERM = "xterm-256color"

[general]
live_config_reload=true
import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/colors.toml"
]
